# Generated by Django 5.2.4 on 2025-07-27 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='html', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='theme',
            field=models.CharField(default='vs-dark', max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
