# Generated by Django 5.2.4 on 2025-07-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_title_snippet_language_snippet_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='theme',
            field=models.CharField(default='light', max_length=50),
        ),
    ]
